[tool.poetry]
name = "tetris-game"
version = "0.1.0"
description = ""
authors = ["maxxof"]
readme = "README.md"
packages = [{include = "tetris_game"}]

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
